// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIEiFrgh_BDtlplkWFNdflyXn_GHi4k4',
    appId: '1:936155044260:web:eca612307f3aa45626c931',
    messagingSenderId: '936155044260',
    projectId: 'medicineapp-27848',
    authDomain: 'medicineapp-27848.firebaseapp.com',
    storageBucket: 'medicineapp-27848.appspot.com',
    measurementId: 'G-FR5B3M7412',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw35tOLvbjxZLoUWN4rjsLbuU_aBSnRvQ',
    appId: '1:936155044260:android:e74e429394f8d3ea26c931',
    messagingSenderId: '936155044260',
    projectId: 'medicineapp-27848',
    storageBucket: 'medicineapp-27848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDha333p6ife8QAjXjoiZW9c-CZ9lfwId4',
    appId: '1:936155044260:ios:87379d27dafee61626c931',
    messagingSenderId: '936155044260',
    projectId: 'medicineapp-27848',
    storageBucket: 'medicineapp-27848.appspot.com',
    iosBundleId: 'com.example.medicineapi',
  );
}
